extends: base.j2
default_block: article

language: fr
menu:
  -
     name: "Projets"
     page: "projets.html"
  -
     name: "Blog"
     page: "blog/"
l10n:
  otherlinks: "Autres liens"
  translations: "Aussi disponible en"
  comments: "Voir les commentaires ou en laisser un (avec Disqus)"
  attachments: "Documents liés"
  tags: "Classé dans"
  share: "Partager cet article"
