extends: base.j2
default_block: article

language: en
menu:
  -
     name: "Projects"
     page: "projects.html"
  -
     name: "Blog"
     page: "blog/"
l10n:
  otherlinks: "Other stuff"
  translations: "Also available in"
  comments: "View or add a new comment (with Disqus)"
  attachments: "Attachments"
  tags: "Filed under"
  share: "Share this article"
